language: php
os: linux
dist: xenial

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

script:
  # Test lint
  - find . -name \*.php -exec php -l "{}" \;

  # Install dev dependencies
  - composer require --dev phpunit/phpunit ^7.5

  # Run phpunit tests
  - make
  - cd src/Tests
  - ../../vendor/bin/phpunit --configuration phpunit.xml

  # Create coverage report
  - sh -c "wget https://scrutinizer-ci.com/ocular.phar"
  - sh -c "php ocular.phar code-coverage:upload --format=php-clover clover.xml"
  
jobs:
  fast_finish: true
